services:
  db:
    image: postgres:17.2-alpine
    container_name: tanstack_start_starter_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - .container/db-data:/var/lib/postgresql/data
    networks:
      - tanstack_start_starter_network

networks:
  tanstack_start_starter_network:
