[phases.setup]
# Force Node.js 22.12+ which Vite 7 requires
nixPkgs = ["nodejs-22_x", "pnpm-9_x"]

[phases.install]
cmds = [
  "npm install -g corepack@0.24.1 && corepack enable",
  # Force complete reinstall to ensure native bindings are installed
  "pnpm install --no-frozen-lockfile --force"
]
