# Explicitly set Node.js version to match .nvmrc
[phases.setup]
nixPkgs = ["nodejs_22", "pnpm-9_x"]

[phases.install]
cmds = [
  "npm install -g corepack@0.24.1 && corepack enable",
  # Force complete reinstall to ensure native bindings are installed
  "pnpm install --no-frozen-lockfile --force"
]

[phases.build]
cmds = ["pnpm build"]

[start]
cmd = "pnpm start"
