[phases.install]
cmds = [
  "npm install -g corepack@0.24.1 && corepack enable",
  # Force reinstall to ensure native bindings are installed
  "pnpm install --no-frozen-lockfile"
]

[phases.build]
cmds = ["pnpm build"]

[start]
cmd = "pnpm start"
