/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root';
import { Route as DashboardRouteImport } from './routes/dashboard/route';
import { Route as AppRouteImport } from './routes/_app/route';
import { Route as DashboardIndexImport } from './routes/dashboard/index';
import { Route as PublicIndexImport } from './routes/_public/index';
import { Route as AuthVerifyImport } from './routes/_auth/verify';
import { Route as AuthSignupImport } from './routes/_auth/signup';
import { Route as AuthSigninImport } from './routes/_auth/signin';
import { Route as AppUserUserIdProfileImport } from './routes/_app/user/$userId.profile';

// Create/Update Routes

const DashboardRouteRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any);

const AppRouteRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRoute,
} as any);

const DashboardIndexRoute = DashboardIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any);

const PublicIndexRoute = PublicIndexImport.update({
  id: '/_public/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any);

const AuthVerifyRoute = AuthVerifyImport.update({
  id: '/_auth/verify',
  path: '/verify',
  getParentRoute: () => rootRoute,
} as any);

const AuthSignupRoute = AuthSignupImport.update({
  id: '/_auth/signup',
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any);

const AuthSigninRoute = AuthSigninImport.update({
  id: '/_auth/signin',
  path: '/signin',
  getParentRoute: () => rootRoute,
} as any);

const AppUserUserIdProfileRoute = AppUserUserIdProfileImport.update({
  id: '/user/$userId/profile',
  path: '/user/$userId/profile',
  getParentRoute: () => AppRouteRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app';
      path: '';
      fullPath: '';
      preLoaderRoute: typeof AppRouteImport;
      parentRoute: typeof rootRoute;
    };
    '/dashboard': {
      id: '/dashboard';
      path: '/dashboard';
      fullPath: '/dashboard';
      preLoaderRoute: typeof DashboardRouteImport;
      parentRoute: typeof rootRoute;
    };
    '/_auth/signin': {
      id: '/_auth/signin';
      path: '/signin';
      fullPath: '/signin';
      preLoaderRoute: typeof AuthSigninImport;
      parentRoute: typeof rootRoute;
    };
    '/_auth/signup': {
      id: '/_auth/signup';
      path: '/signup';
      fullPath: '/signup';
      preLoaderRoute: typeof AuthSignupImport;
      parentRoute: typeof rootRoute;
    };
    '/_auth/verify': {
      id: '/_auth/verify';
      path: '/verify';
      fullPath: '/verify';
      preLoaderRoute: typeof AuthVerifyImport;
      parentRoute: typeof rootRoute;
    };
    '/_public/': {
      id: '/_public/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof PublicIndexImport;
      parentRoute: typeof rootRoute;
    };
    '/dashboard/': {
      id: '/dashboard/';
      path: '/';
      fullPath: '/dashboard/';
      preLoaderRoute: typeof DashboardIndexImport;
      parentRoute: typeof DashboardRouteImport;
    };
    '/_app/user/$userId/profile': {
      id: '/_app/user/$userId/profile';
      path: '/user/$userId/profile';
      fullPath: '/user/$userId/profile';
      preLoaderRoute: typeof AppUserUserIdProfileImport;
      parentRoute: typeof AppRouteImport;
    };
  }
}

// Create and export the route tree

interface AppRouteRouteChildren {
  AppUserUserIdProfileRoute: typeof AppUserUserIdProfileRoute;
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppUserUserIdProfileRoute: AppUserUserIdProfileRoute,
};

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
);

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute;
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
};

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
);

export interface FileRoutesByFullPath {
  '': typeof AppRouteRouteWithChildren;
  '/dashboard': typeof DashboardRouteRouteWithChildren;
  '/signin': typeof AuthSigninRoute;
  '/signup': typeof AuthSignupRoute;
  '/verify': typeof AuthVerifyRoute;
  '/': typeof PublicIndexRoute;
  '/dashboard/': typeof DashboardIndexRoute;
  '/user/$userId/profile': typeof AppUserUserIdProfileRoute;
}

export interface FileRoutesByTo {
  '': typeof AppRouteRouteWithChildren;
  '/signin': typeof AuthSigninRoute;
  '/signup': typeof AuthSignupRoute;
  '/verify': typeof AuthVerifyRoute;
  '/': typeof PublicIndexRoute;
  '/dashboard': typeof DashboardIndexRoute;
  '/user/$userId/profile': typeof AppUserUserIdProfileRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  '/_app': typeof AppRouteRouteWithChildren;
  '/dashboard': typeof DashboardRouteRouteWithChildren;
  '/_auth/signin': typeof AuthSigninRoute;
  '/_auth/signup': typeof AuthSignupRoute;
  '/_auth/verify': typeof AuthVerifyRoute;
  '/_public/': typeof PublicIndexRoute;
  '/dashboard/': typeof DashboardIndexRoute;
  '/_app/user/$userId/profile': typeof AppUserUserIdProfileRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | ''
    | '/dashboard'
    | '/signin'
    | '/signup'
    | '/verify'
    | '/'
    | '/dashboard/'
    | '/user/$userId/profile';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | ''
    | '/signin'
    | '/signup'
    | '/verify'
    | '/'
    | '/dashboard'
    | '/user/$userId/profile';
  id:
    | '__root__'
    | '/_app'
    | '/dashboard'
    | '/_auth/signin'
    | '/_auth/signup'
    | '/_auth/verify'
    | '/_public/'
    | '/dashboard/'
    | '/_app/user/$userId/profile';
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren;
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren;
  AuthSigninRoute: typeof AuthSigninRoute;
  AuthSignupRoute: typeof AuthSignupRoute;
  AuthVerifyRoute: typeof AuthVerifyRoute;
  PublicIndexRoute: typeof PublicIndexRoute;
}

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthVerifyRoute: AuthVerifyRoute,
  PublicIndexRoute: PublicIndexRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_app",
        "/dashboard",
        "/_auth/signin",
        "/_auth/signup",
        "/_auth/verify",
        "/_public/"
      ]
    },
    "/_app": {
      "filePath": "_app/route.tsx",
      "children": [
        "/_app/user/$userId/profile"
      ]
    },
    "/dashboard": {
      "filePath": "dashboard/route.tsx",
      "children": [
        "/dashboard/"
      ]
    },
    "/_auth/signin": {
      "filePath": "_auth/signin.tsx"
    },
    "/_auth/signup": {
      "filePath": "_auth/signup.tsx"
    },
    "/_auth/verify": {
      "filePath": "_auth/verify.tsx"
    },
    "/_public/": {
      "filePath": "_public/index.tsx"
    },
    "/dashboard/": {
      "filePath": "dashboard/index.tsx",
      "parent": "/dashboard"
    },
    "/_app/user/$userId/profile": {
      "filePath": "_app/user/$userId.profile.tsx",
      "parent": "/_app"
    }
  }
}
ROUTE_MANIFEST_END */
